require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Editor::TranslationsController do

  # This should return the minimal set of attributes required to create a valid
  # Editor::Translation. As you add validations to Editor::Translation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Editor::TranslationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all editor_translations as @editor_translations" do
      translation = Editor::Translation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:editor_translations).should eq([translation])
    end
  end

  describe "GET show" do
    it "assigns the requested editor_translation as @editor_translation" do
      translation = Editor::Translation.create! valid_attributes
      get :show, {:id => translation.to_param}, valid_session
      assigns(:editor_translation).should eq(translation)
    end
  end

  describe "GET new" do
    it "assigns a new editor_translation as @editor_translation" do
      get :new, {}, valid_session
      assigns(:editor_translation).should be_a_new(Editor::Translation)
    end
  end

  describe "GET edit" do
    it "assigns the requested editor_translation as @editor_translation" do
      translation = Editor::Translation.create! valid_attributes
      get :edit, {:id => translation.to_param}, valid_session
      assigns(:editor_translation).should eq(translation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Editor::Translation" do
        expect {
          post :create, {:editor_translation => valid_attributes}, valid_session
        }.to change(Editor::Translation, :count).by(1)
      end

      it "assigns a newly created editor_translation as @editor_translation" do
        post :create, {:editor_translation => valid_attributes}, valid_session
        assigns(:editor_translation).should be_a(Editor::Translation)
        assigns(:editor_translation).should be_persisted
      end

      it "redirects to the created editor_translation" do
        post :create, {:editor_translation => valid_attributes}, valid_session
        response.should redirect_to(Editor::Translation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved editor_translation as @editor_translation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Editor::Translation.any_instance.stub(:save).and_return(false)
        post :create, {:editor_translation => {}}, valid_session
        assigns(:editor_translation).should be_a_new(Editor::Translation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Editor::Translation.any_instance.stub(:save).and_return(false)
        post :create, {:editor_translation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested editor_translation" do
        translation = Editor::Translation.create! valid_attributes
        # Assuming there are no other editor_translations in the database, this
        # specifies that the Editor::Translation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Editor::Translation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => translation.to_param, :editor_translation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested editor_translation as @editor_translation" do
        translation = Editor::Translation.create! valid_attributes
        put :update, {:id => translation.to_param, :editor_translation => valid_attributes}, valid_session
        assigns(:editor_translation).should eq(translation)
      end

      it "redirects to the editor_translation" do
        translation = Editor::Translation.create! valid_attributes
        put :update, {:id => translation.to_param, :editor_translation => valid_attributes}, valid_session
        response.should redirect_to(translation)
      end
    end

    describe "with invalid params" do
      it "assigns the editor_translation as @editor_translation" do
        translation = Editor::Translation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Editor::Translation.any_instance.stub(:save).and_return(false)
        put :update, {:id => translation.to_param, :editor_translation => {}}, valid_session
        assigns(:editor_translation).should eq(translation)
      end

      it "re-renders the 'edit' template" do
        translation = Editor::Translation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Editor::Translation.any_instance.stub(:save).and_return(false)
        put :update, {:id => translation.to_param, :editor_translation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested editor_translation" do
      translation = Editor::Translation.create! valid_attributes
      expect {
        delete :destroy, {:id => translation.to_param}, valid_session
      }.to change(Editor::Translation, :count).by(-1)
    end

    it "redirects to the editor_translations list" do
      translation = Editor::Translation.create! valid_attributes
      delete :destroy, {:id => translation.to_param}, valid_session
      response.should redirect_to(editor_translations_url)
    end
  end

end
