---
language: ruby
cache: bundler
rvm:
  - 2.3.1

before_script:
  - cp config/database.travis config/database.yml
  - bundle exec rake bootstrap

services:
  - mysql

after_success:
  - ssh -o StrictHostKeyChecking=no lvee@lvee.org
