
* Баги сайта

# [ND] В профиле у отменившихся от winter lvee чуваков, в том числе и
   у меня, стоит запись о том что мы участвовали в зимней конфе.

You have participated:

LVEE 2010 (July 01, 2010 – July 04, 2010)
LVEE 2011 (June 30, 2011 – July 03, 2011)
LVEE Winter 2012 (February 10, 2012 – February 12, 2012)
Feature requests:

- Дубликат переключалки языков внизу, где-нибудь на уровне эмблемы creative commons
- В самом низу, ниже эмблемы creative commons – строка с url
  git-версии движка и лицензией (скопировать как это сделано на
  conference.linux.lviv.ua)
- В блоке новостей на главной странице добавить гиперссылку в виде
  многоточия после каждой из трех аннотаций, как на webcamp.in.ua. Это
  важно потому что кликабельный заголовок новости не совпадает по
  цвету с гиперссылками, и наличие основного текста новости многими
  может оставаться незамеченным.
- Редактор меню – пусть даже не интерактивный, пусть нечто типа
  редактора языков. Но он реально нужен.
- Редактор шапки – по аналогии с редактором спонсоров.

- (high priority) Админке пользователей нужен фильтр по конференциям в
  виде выпадающего списка, по-умолчанию установленный на последнюю
  конференцию (!!!), а кроме того содержащий каждую из прошедших
  конференций и пункт “Все конференции”. Причина – уже сейчас
  приходилось ждать несколько секунд, пока этот список
  загрузится. Летом (после интеграции очередных 200 человек из foss
  lviv) все станет еще кошмарнее, но главное, эти тормоза – ради
  вывода 10% полезной и 90% абсолютно ненужной информации. При этом
  разбивка списка на несколько страниц совершенно не годится – просто
  потому, что тогда поиск нужного человека (посмотреть телефон или
  послать почту) станет еще неудобнее: листать 90% мусора, прыгая по
  гиперссылкам, еще хуже :)


* [ND] True Story 1 “Transport”:

Как организатор-расселятор хочу иметь возможность редактировать
количество доступных для поездки маршруток в/с места проведения,
наличие в них свободных мест и время отъезда из точки сбора.

Чтобы не искать эту информацию на страничках вики, а также сэкономить
время на вытягивание данной информации

Чтобы2: как пользователю мне было удобно выбрать нужную маршрутку и
зарезервировать в ней место(а) из предложенных либо стать в очередь
если мест не хватает.

** Идеи:
- Создать страничку с чек-боксом и привязкой к аккаунту чтобы
   зареганые пользователи смогли поставить галочку напротив нужной
   маршрутки. Эта инфа собирается в админке на соответствующей
   странице, следовательно, можно увидеть тех кто записался и кто не
   записался на транспорт. Также на этой же страничке было бы не плохо
   иметь список тех кто указал что поедет на маршрутке, но никуда не
   вписался + возможность отправить всем не записавшимся
   письмо-напоминание, о том что необходимо записаться в
   маршрутку. Письмо-напоминание должно быть редактируемым. Страничка
   с чек-боксом должна быть также редактируемой для пользователя с
   админскими правами, чтобы иметь возможность перемещать людей из
   одной маршрутки в другую (с автоматическим уведомлением тех кого
   куда переместили и кого вписали, это было бы ваще зашибись) и т.п.
- Иная реализация – это добавить чек-бокс (или выпадающее меню) с
  маршрутками (время отправления, номер места, откуда отбывает) во 2ую
  анкету (ту которую заполняют после подтверждения регистрации). Поле
  транспорт обязательное! Опять же эту инфу надо собирать где-то в
  разделе админки, чтобы можно было редактировать, видеть список тех
  кто вписался а кто еще нет, написать письмо-напоминание, распечатать
  список и остальными фичами описанными в первой идеи.

Other:
Если участник отменил регистрацию – запись о проезде должна удаляться автоматически.

================

* [ND] True Story 2 “Accommodation. С кем же я хочу жить …”:
Как организатор-расселятор хочу иметь возможность расселять людей используя возможности админки lvee

- Чтобы сэкономить время

- Чтобы2 своевременно уведомить зарегистрировавшихся о плане
  расселения

- Чтобы3 использовать данную информацию на месте проведения
  конференции

- Чтобы4 улучшить самочувствие и так уставших от организации
  конференции организаторов конференции :)

Идеи:
** (простая)
В графе “Пожелания к расселению” во 2ой анкете (ту что заполняют
участники после подтверждения регистрации) разместить выпадающий
список с участниками, и пусть вибирает с кем он хочет жить. Основные
возможности, которые будут доступны пользователю (поле обязательное
для заполнения!):

- Выбрать более 1 участника
-  “Мне все равно”
- “С тем кого с собой зарегал” – Еду с женой/мужем/девушкой/парнем
- “С тем кого с собой зарегал” – Еду с другом/подругой, если есть возможность, поселите нас вместе, если нет – можете расселить в отдельные комнаты ;(
- “В расселении не нуждаюсь”
Также должна где-нибудь в админке быть страничка где администратор
указывает наличие свободных мест по домикам и по комнатам. Следующий
этап – скрестить информацию полученную от пользователей с имеющимся
количеством комнат и случится магия – после нажатия на магическую
кнопку “Расселить”, организатор-расселятор получает план
расселения. При этом необходимо учитывать даты заезда и отъезда
участников! План должен быть редактируемым, т.е. организатор может
вносить свои правки и система автоматически перерисует план, либо
предложит варианты.

** (гибридная). 
Создать страничку на сайте, с привязкой к пользовательским
аккаунтам. Пользователи сами себя расселяют в имеющиеся в наличии
места. При этом:

- Если человек указал у себя в анкете, что он приедет в Пятницу
  (Субботу) автоматом проставлять что комната будет занята с Пятницы
  (Субботы) по какой день (если участник будет только 2-3 дня).
- Участник не может редактировать изменения внесенные другими участниками
- Админ может редактировать изменения внесенные любыми участниками.
- Участник может вносить изменения только за себя и за человека которого он везет с собой, если этот человек предварительно не зарегистрировался сам.
- В режиме редактирования, админ сайта должен видеть статус участника (представитель спонсора, докладчик, просто участник, организатор), дату приезда/отъезда участника.
- 1 участник – 1 койко-место.
- Админ может расселять участиков на одно же место, если даты их
  пребывания не совпадают. Сюда же, админ может менять место
  пребывания участника по дням в разных комнатах (на случай цунами), а
  именно вписывать одного и того же участника в разные комнаты на
  разные дни пребывания. Админ должен иметь возможность указывать дни
  пребывания участника в комнатах.
- Также в режиме редактирования странички, админ должен иметь
  возможность посмотреть список не расселившихся участников, написать
  им всем, либо выборочно, письмо-напоминание.
- Под участниками подразумеваются все подтвержденные организаторами
  пользователи зарегистрировавшиеся на предстоящую конференцию.
- В случае отказа участника от участия в конференции, запись о
  расселении автоматически удаляется, чтобы дать возможность другим
  участникам записаться на его место.
- Админ должен иметь возможность экспортировать данную информацию в
  cvs формате (поля обговорим отдельно).

Итого: Организатор-расселятор приезжает на место проведения
конференции с планом по расселению. Участники знают предварительный
план по расселению.

================

* [ND] True Story 3 “Food”
Как организатор я хочу видеть сколько необходимо заказывать завтраков, обедов, ужинов, какие порции заказывать (вегетарианские или обычные)
Чтобы предварительно сделать заказ блюд на турбазе

Описание:
1. Во второй анкете вместо редактируемого поля “Предпочтения в питании” сделать селектор с двумя полями: “Вегетарианец” и “Ем все”
2. На отдельной страничке, либо где-то еще в админке, показывать инфу по дням пребывания и количеству вегетарианских и обычных блюд заказываемых на завтрак, обед, ужин.

================

Coming soon:

* [ND] True Story 4 “QR-коды при регистрации”

* [ND] True Story 5 “QR-коды для обмена участниками контактами”

* [ND] True Story 6 “Sponsors page. Требования к предоставляемым макетам”

* [ND] True Story 7 “Offline mode/Syncing”

* [ND] True Story 8 “Reporters page. Сводная табличка докладчиков” (возможность отслеживать участников, изъявивших желание прочитать доклад)

* [ND] True Story 9 “Notifications”
