development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: P@ssw0rd
  database: lvee_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: P@ssw0rd
  database: lvee_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: P@ssw0rd
  database: lvee_development
